name: TFLint

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  tflint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup TFLint
        uses: terraform-linters/setup-tflint@v4

      - name: Run TFLint
        run: |
          tflint --init
          tflint
